FROM python:3.12-slim

# Системные зависимости
RUN apt-get update && apt-get install -y \
    libreoffice \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

# Устанавливаем зависимости
COPY pyproject.toml poetry.lock* /app/
RUN poetry config virtualenvs.create false \
    && poetry install --no-root --no-interaction --no-ansi

# Копируем код
COPY . /app

# Папка для медиа
RUN mkdir -p /app/media/temp

# Прокси/порт
EXPOSE 8000

# Prod CMD — без reload
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
